# profile
spring:
  profiles:
    active: dev
  # spring devtools
  devtools:
    restart:
      enabled: true

# mybatis plus
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  # 实体类扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.ataraxia.domain
  global-config:
    # 数据库相关配置
    db-config:
      # 主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      # 字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      # 驼峰下划线转换
      column-underline: true
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 0
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 1
    banner: false
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'

